version: '3.8'

services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile 
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: nextauth-app
    working_dir: /app
    ports:
      - "3001:3000" 
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: ["npm", "run", "start"]  